### PR TITLE
fixing pathways

### PR DESCRIPTION
**Pull request by Budalebah**

### CODE REVIEW

**Comment by victorchimakanu** [comment]
Hi @Budalebah. Thanks for your contribution!

Would you like to join Bagels Dev Forum? Please drop a "hi" in the general channel so I can add you 🙂

https://discord.gg/G8R4Y8Mc

**Comment by Budalebah** [comment]
Hey ser i am already in , my discord name : halo (haloperidol_)

**Comment by Budalebah** [comment]
Can you merge to be closed. thank you

**Comment by victorchimakanu** [comment]
Hi @Budalebah,

I have reviewed the changes and they meet all the requirements. The code is well-implemented and addresses the issue effectively.
Thank you for your contribution!

 I approve to merge this PR @BidhanRoy.

**Review by victorchimakanu — APPROVED** [review]
Hi @Budalebah,

I have reviewed the changes and they meet all the requirements. The code is well-implemented and addresses the issue effectively.
Thank you for your contribution!

 I approve to merge this PR @BidhanRoy.

**Pull request merged**
