### PR TITLE
Review "Upload file" function 

### PR DESCRIPTION
**Pull request by victorchimakanu**
To test this function:

1. update your node_modules/bageldb-beta/src/api.js file with the api.js file in the pull request 
2. simply run `node name_of_file.js`

### CODE REVIEW

**Comment by victorchimakanu** [comment]
Currently working on Query function , need help understanding the parameters in the query function. Will contact ismail to explain further.

Here's my testing code for this function:

```js
import { Settings, Client } from 'bageldb-beta'

// Settings config
const settings = new Settings({
  bagel_api_impl: 'rest',
  bagel_server_host: 'api.bageldb.ai',
})

const client = new Client(settings)

const payload = {
  clusterId: 'b59195f2-030e-430d-8a25-29dbf79aa03e',
  queryEmbeddings: '',
  nResults: 10,
  where: {},
  whereDocument: {},
  include: ['metadatas', 'documents', 'distances'],
  queryTexts: null,
  apiKey: '4gB2wJPByf8qnUihAmH8dgbGYsZESEOH',
}
const queryAsset = async () => {
  // get version
  const asset = await client.query(payload)
  console.log(asset)
}

queryAsset()


```

**Comment by victorchimakanu** [comment]
Functions to add text embedded data in vector asset (Working smoothly) and query vector asset (WIP) has been added.

1. To test out the query function, update your api.js is your `node_modules folder/bageldb-beta` with the one in this pull request. and run this code. This is still a work in progress

```js
import { Settings, Client } from "bageldb-beta";

// Settings config
const settings = new Settings({
  bagel_api_impl: "rest",
  bagel_server_host: "api.bageldb.ai",
});

const client = new Client(settings);

const assetId = 'f4013273-03fa-4d2a-bfb4-d36bda4d5a1c';
const apiKey = '4gB2wJPByf8qnUihAmH8dgbGYsZESEOH';

const payload = {
  "where": {},
  "where_document": {},
  "n_results": 1,
  "include": [
    "metadatas",
    "documents",
    "distances"
  ],
  "query_texts": [
    "apple"
  ],
  "padding": false
};

const queryVectorAsset = async () => {
  try {
    console.log('Sending query with payload:', payload);
    
    const response = await client.query_data_from_asset(assetId, payload, apiKey);

    console.log('Response received:', response);
  } catch (error) {
    if (error.response) {
      // Log the error response from the server
      console.error('Error response:', error.response.data);
    } else {
      // Log any other errors
      console.error('Internal error:', error.message);
    }
  }
};

queryVectorAsset();
```

2. Add data to vector assets function is working perfectly, you can find the testing code in the readme , simply copy/paste and run after you have updated your api.js file in the previous step

**Comment by BidhanRoy** [comment]
Can you fix the conflicts so that I can merge?

**Comment by victorchimakanu** [comment]
@BidhanRoy All checks have been resolved

**Comment by victorchimakanu** [comment]
Testing code for update function 

```js
import { Settings, Client } from 'bageldb-beta'

// Settings config
const settings = new Settings({
  bagel_api_impl: 'rest',
  bagel_server_host: 'api.bageldb.ai',
})

const client = new Client(settings)

const cluster_Id = 'f4013273-03fa-4d2a-bfb4-d36bda4d5a1c'
const apiKey = '4gB2wJPByf8qnUihAmH8dgbGYsZESEOH'

const payload = {
  embeddings: ['Hi'],
  metadatas: [{ 'making it fine': 'let us finish it well', meta: 'fast' }],
  documents: ['everyone is good', 'just search for it and you will find it'],
  ids: ['tyuiop[lkbjkoj'],
  increment_index: true,
}
const update = async () => {
  try {
    console.log('Sending request with payload:', payload)

    const response = await client.update_cluster(cluster_Id, payload, apiKey)

    console.log('Response received:', response)
  } catch (error) {
    console.error('Error update cluster embedding:', error)
  }
}

update()

```

**Comment by victorchimakanu** [comment]
To test these files. 

1. Update your api.js folder located in your node modules (update it with the one in this PR)
2. Run the "update asset" code located in the javascript readme of this PR
3. Code for Query asset is located in the readme as well , but still a work in progress 
4. Run using node

**Pull request merged**
